name: Procurement
description: "Manages the purchase and utilization of goods and services for chair activities."
title: "Procurement: [Type] [Quantity] [Product name] from [Vendor] for [User(s)] on [Purchase date]"
assignees:
  - sjinko
projects:
  - "CUPUM/33"
  - "CUPUM/145"
body:

- type: markdown
  attributes:
    value: |
      ## Procurement process

      This issue concerns a purchase, a subscription or a contract engaged by the UNESCO Chair in Urban Landscape.
      For certain conventionned products (e.g. computers) and procurements above a certain amount (5000 CAD), refer to the University’s guidelines
      This does not include travel and representations fees nor salaries.
      
      This includes consumable and durable products and services:
      - Consumable:
        - Office supplies
        - Subscription
      - Equipment:
        - Books
        - Software
        - Equipment
        - Furniture
      - Reception fees
        - Food and drinks
      - Contracts 
        - Honoraries
        - Subcontractors
      - Other
      
      Use ONE issue per product/service/bundle/contract (the markdown content can be copy-pasted on blank issues).

- type: dropdown
  attributes:
    label: "Type"
    description: "Select one of the following"
    options:
      - Office supplies
      - Subscription
      - Book
      - Software (one-time purchase)
      - Equipment
      - Furniture
      - Food and drinks
      - Honoraries
      - Subconstractors
      - Other
  validations:
    required: true

- type: input
  attributes:
    label: "Quantity"
    description: "How many units are in the product/service (e.g., items, hours, counts, etc.)."
  validations:
    required: true

- type: input
  attributes:
    label: "Product name"
    description: "Give precise name, model, and version of the purchased product or service."
  validations:
    required: true

- type: input
  attributes:
    label: "Product brand"
    description: "Who produces this product or service, put 'TBD' if unknown."
  validations:
    required: true

- type: input
  attributes:
    label: "Provider"
    description: "Company name selling the product or service, put 'TBD' if unknown."
  validations:
    required: true

- type: input
  attributes:
    label: "User(s)"
    description: "Who will be using this product or service, put 'All' if for everyone."
  validations:
    required: false

- type: textarea
  attributes:
    label: "Reason for purchase"
    description: "Explain the motivation and context for which this purchase is made."
  validations:
    required: true

- type: input
  attributes:
    label: "Price"
    description: "Indicate the actual or estimated total price for all items including taxes."
  validations:
    required: true

- type: input
  attributes:
    label: "Project code"
    description: "Specify which financial project has been used, put 'Pending' if unknown."
  validations:
    required: true

- type: input
  attributes:
    label: "Quote, Invoice or Receipt"
    description: "Drop proofs of purchase when available"
  validations:
    required: false

- type: input
  attributes:
    label: "Serial, license or contract number"
    description: "Input serial number, license number or contract number after reception, put 'Pending' if not received or 'NA' if not applicable."
  validations:
    required: true

- type: input
  attributes:
    label: "Location"
    description: "Room number, equipment or URL, put 'TBD' if unknown."
  validations:
    required: true

- type: textarea
  attributes:
    label: "Warranty details"
    description: "Duration and conditions of the warranty"
  validations:
    required: false

- type: input
  attributes:
    label: "Photo"
    description: "Drop photo of purchased items or screenshot for online"
  validations:
    required: false

- type: checkboxes
  attributes:
    label: "List of actions"
    description: "Please complete in order"
    options:
      - label: "Action: Fill form"
      - label: "Action: Ask @sjinko to confirm/speficy financial projet to use"
      - label: "Action: Make purchase"
      - label: "Action: Add associated projects to issue (e.g. equipment bought for specific project)"
      - label: "Action: Drop payment receipt in issue main box"
      - label: "Action: Receive purchase"
      - label: "Action: Add serial, licence or contract number (if applicable)"
      - label: "Action: Add warranty dates and conditions (if applicable)"
      - label: "Action: Add photo of actual product or screenshot if digital"
      - label: "Action: Create a 'Reimbursement claim' if paid by member or employee"
      - label: "Action: Add any updates (lost, broken, stolen, transfer) in comments"

- type: markdown
  attributes:
    value: |
      ### List of users/borrowers (for consumables or equipment only)
      - [ ] Task: Borrowed by [name] on [start date] until [end date]
      - [ ] Task: Borrowed by [name] on [start date] until [end date]
