name: Contact
description: "Manage contact information for members and external partners"
title: "Contact: [Full Name], [Position] at [Organization]"
projects: ["CUPUM/179"]
body:

# Guidelines
- type: markdown
  attributes:
    value: |
      ## General
      This template manages the registration, tracking and note-taking about contacts of the UNESCO Chair in Urban Landscape. This concerns both the contact information of members and external leads.

      ## Repositories
      Make sure that you are creating the contact in the right repository. Project or strategy based contacts should be located in the associated repository. For general contacts, such as chairmembers, use the _General_ repository.

# Contact information
- type: input
  id: first_name
  attributes:
    label: First  
    description: First name
  validations:
    required: true

- type: input
  id: last_name
  attributes:
    label: Last
    description: Last name
  validations:
    required: true

- type: dropdown
  id: type
  attributes:
    label: Contact type
    options:
      - UdeM employee
      - UdeM student
      - External academic
      - External student
      - External non-academic
  validations:
    required: true

- type: dropdown
  id: membership
  attributes:
    label: Membership status
    options:
      - Non member
      - Core member
      - Associate member
      - Affiliate member
      - Alumni member
  validations:
    required: true

- type: input
  id: membership_start
  attributes:
    label: Membership start date
    description: yyyy-mm-dd
  validations:
    required: false

- type: input
  id: membership_end
  attributes:
    label: Membership end date
    description: yyyy-mm-dd
  validations:
    required: false

- type: input
  id: organization
  attributes:
    label: Organization
    description: Organization to which they are associated mainly
  validations:
    required: true

- type: input
  id: position
  attributes:
    label: Positions
    description: Exact roles within their organization
  validations:
    required: false

- type: input
  id: email_1
  attributes:
    label: Email_1
    description: Email address (professional, ideally)
    placeholder: "ex. email@example.com"
  validations:
    required: false

- type: input
  id: email_2
  attributes:
    label: Email_2
    description: Email address (personal, ideally)
    placeholder: "ex. email@example.com"
  validations:
    required: false

- type: input
  id: phone_1
  attributes:
    label: Phone_1
    description: Phone number, including international code (professional, ideally)
    placeholder: "ex. +X XXX XXX-XXXX"
  validations:
    required: false

- type: input
  id: phone_2
  attributes:
    label: Phone_2
    description: Phone number, including international code (personal, ideally)
    placeholder: "ex. +X XXX XXX-XXXX"
  validations:
    required: false

- type: dropdown
  id: lead_status
  attributes:
    label: Lead status
    options:
      - New
      - Open
      - In progress
      - Open deal
      - Unqualified
      - Attempted to contact
      - Connected
      - Bad timing
  validations:
    required: false

- type: input
  id: content_topic
  attributes:
    label: Favorite content topic
    description: What’s their main interest professional or personnal
  validations:
    required: false

- type: input
  id: pref_channel
  attributes:
    label: Preferred channel
    description: How do they prefer to be contacted
  validations:
    required: false

- type: textarea
  id: notes
  attributes:
    label: Notes
    description: Important information about the contact.
  validations:
    required: false

- type: checkboxes
  id: actions  
  attributes:
    label: List of actions (for leads)
    description: Check completed actions
    options:
      - label: "Action: Register contact"
      - label: "Action: Identify lead relevant background"
      - label: "Action: Identify proper contact channel"
      - label: "Action: Craft personalized message that provides value for them and call to action"
      - label: "Action: Message/call contact"
      - label: "Follow up contact"
